name: SDL Project CI

on:
  push:
    branches: [main]
  
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Install SDL2
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests
        run: |
          cd build
          ./the_penitence

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

      - name: If fail kakao talk to me
        if: failure()
        # if: always()
        uses: Alfex4936/kakaotalk-ci-action@main
        with:
          kakao_access_token: ${{secrets.KAKAO_ACCESS_TOKEN}}
          function_name: send_to_me_custom
          template_id: "1120209"
          template_args: '{"title": "!! CI FAILED !!", "desc": "ISSUE"}'
