name: SDL Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gcc, clang]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.21.1'

    - name: Install SDL2 dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev
        
    - name: Install SDL2 dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install sdl2
        
    - name: Install SDL2 dependencies on Windows
      run: |
        wget https://www.libsdl.org/release/SDL2-2.26.0-win64-x64.zip
        unzip SDL2-2.26.0-win64-x64.zip -d C:/libs/SDL2
      
    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Run tests
      run: |
        cd build
        ctest -V
    - name: If fail kakao talk to me
      if: failure()
      # if: always()
      uses: Alfex4936/kakaotalk-ci-action@main
      with:
        kakao_access_token: ${{secrets.KAKAO_ACCESS_TOKEN}}
        function_name: send_to_me_custom
        template_id: "1120209"
        template_args: '{"title": "!! CI FAILED !!", "desc": "ISSUE"}'
